using System.ComponentModel;

namespace PSC.Blazor.Components.MarkdownEditor.Enums
{
    /// <summary>
    /// Themes for the CodeMirror editor
    /// </summary>
    public enum EditorTheme
    {
        [Description("default")] Default,
        
        [Description("abbott")] Abbott,
        [Description("abcdef")] Abcdef,
        [Description("ambiance")] Ambiance,
        [Description("ambiance-mobile")] AmbianceMobile,
        [Description("ayu-dark")] AyuDark,
        [Description("ayu-mirage")] AyuMirage,
        [Description("base16-dark")] Base16Dark,
        [Description("base16-light")] Base16Light,
        [Description("bespin")] Bespin,
        [Description("blackboard")] Blackboard,
        [Description("cobalt")] Cobalt,
        [Description("colorforth")] Colorforth,
        [Description("darcula")] Darcula,
        [Description("dracula")] Dracula,
        [Description("duotone-dark")] DuotoneDark,
        [Description("duotone-light")] DuotoneLight,
        [Description("eclipse")] Eclipse,
        [Description("elegant")] Elegant,
        [Description("erlang-dark")] ErlangDark,
        [Description("gruvbox-dark")] GruvboxDark,
        [Description("hopscotch")] Hopscotch,
        [Description("icecoder")] Icecoder,
        [Description("idea")] Idea,
        [Description("isotope")] Isotope,
        [Description("juejin")] Juejin,
        [Description("lesser-dark")] LesserDark,
        [Description("liquibyte")] Liquibyte,
        [Description("lucario")] Lucario,
        [Description("material")] Material,
        [Description("material-darker")] MaterialDarker,
        [Description("material-ocean")] MaterialOcean,
        [Description("material-palenight")] MaterialPalenight,
        [Description("mbo")] Mbo,
        [Description("mdn-like")] MdnLike,
        [Description("midnight")] Midnight,
        [Description("monokai")] Monokai,
        [Description("moxer")] Moxer,
        [Description("neat")] Neat,
        [Description("neo")] Neo,
        [Description("night")] Night,
        [Description("nord")] Nord,
        [Description("oceanic-next")] OceanicNext,
        [Description("panda-syntax")] PandaSyntax,
        [Description("paraiso-dark")] ParaisoDark,
        [Description("paraiso-light")] ParaisoLight,
        [Description("pastel-on-dark")] PastelOnDark,
        [Description("railscasts")] Railscasts,
        [Description("rubyblue")] Rubyblue,
        [Description("seti")] Seti,
        [Description("shadowfox")] Shadowfox,
        [Description("solarized")] Solarized,
        [Description("ssms")] Ssms,
        [Description("the-matrix")] TheMatrix,
        [Description("tomorrow-night-bright")] TomorrowNightBright,
        [Description("tomorrow-night-eighties")] TomorrowNightEighties,
        [Description("ttcn")] Ttcn,
        [Description("twilight")] Twilight,
        [Description("vibrant-ink")] VibrantInk,
        [Description("xq-dark")] XqDark,
        [Description("xq-light")] XqLight,
        [Description("yeti")] Yeti,
        [Description("yonce")] Yonce,
        [Description("zenburn")] Zenburn,
        [Description("3024-day")] Day3024,
        [Description("3024-night")] Night3024,
    }
}